"""Initial schema

Revision ID: 14f15512080a
Revises: 
Create Date: 2025-11-24 20:00:38.747016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f15512080a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=False)
    op.create_table('chaves_pix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CPF', 'CNPJ', 'EMAIL', 'TELEFONE', 'ALEATORIA', name='tipochavepix'), nullable=False),
    sa.Column('chave', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('agencia', sa.String(length=10), nullable=False),
    sa.Column('conta', sa.String(length=20), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chaves_pix_chave'), 'chaves_pix', ['chave'], unique=True)
    op.create_index(op.f('ix_chaves_pix_id'), 'chaves_pix', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_pessoa', sa.Enum('PF', 'PJ', name='tipopessoa'), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cliente_cpf_cnpj', 'clientes', ['cpf_cnpj'], unique=False)
    op.create_index('idx_cliente_data_nascimento', 'clientes', ['data_nascimento'], unique=False)
    op.create_index('idx_cliente_nome_ativo', 'clientes', ['nome', 'ativo'], unique=False)
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('configuracoes_boleto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banco_codigo', sa.String(length=3), nullable=False),
    sa.Column('banco_nome', sa.String(length=100), nullable=False),
    sa.Column('agencia', sa.String(length=10), nullable=False),
    sa.Column('agencia_dv', sa.String(length=1), nullable=True),
    sa.Column('conta', sa.String(length=20), nullable=False),
    sa.Column('conta_dv', sa.String(length=2), nullable=False),
    sa.Column('cedente_nome', sa.String(length=255), nullable=False),
    sa.Column('cedente_documento', sa.String(length=14), nullable=False),
    sa.Column('cedente_endereco', sa.String(length=500), nullable=True),
    sa.Column('carteira', sa.String(length=3), nullable=False),
    sa.Column('convenio', sa.String(length=20), nullable=True),
    sa.Column('variacao_carteira', sa.String(length=3), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.Column('local_pagamento', sa.String(length=255), nullable=False),
    sa.Column('percentual_juros', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('percentual_multa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_boleto_id'), 'configuracoes_boleto', ['id'], unique=False)
    op.create_table('contas_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGA', 'RECEBIDA', 'ATRASADA', 'CANCELADA', name='statusfinanceiro'), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('categoria_financeira', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conta_pagar_categoria', 'contas_pagar', ['categoria_financeira'], unique=False)
    op.create_index('idx_conta_pagar_emissao', 'contas_pagar', ['data_emissao'], unique=False)
    op.create_index('idx_conta_pagar_fornecedor_status', 'contas_pagar', ['fornecedor_id', 'status'], unique=False)
    op.create_index('idx_conta_pagar_vencimento_status', 'contas_pagar', ['data_vencimento', 'status'], unique=False)
    op.create_index(op.f('ix_contas_pagar_categoria_financeira'), 'contas_pagar', ['categoria_financeira'], unique=False)
    op.create_index(op.f('ix_contas_pagar_data_emissao'), 'contas_pagar', ['data_emissao'], unique=False)
    op.create_index(op.f('ix_contas_pagar_data_pagamento'), 'contas_pagar', ['data_pagamento'], unique=False)
    op.create_index(op.f('ix_contas_pagar_data_vencimento'), 'contas_pagar', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_contas_pagar_descricao'), 'contas_pagar', ['descricao'], unique=False)
    op.create_index(op.f('ix_contas_pagar_documento'), 'contas_pagar', ['documento'], unique=False)
    op.create_index(op.f('ix_contas_pagar_fornecedor_id'), 'contas_pagar', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_contas_pagar_id'), 'contas_pagar', ['id'], unique=False)
    op.create_index(op.f('ix_contas_pagar_status'), 'contas_pagar', ['status'], unique=False)
    op.create_table('contas_receber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_recebido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGA', 'RECEBIDA', 'ATRASADA', 'CANCELADA', name='statusfinanceiro'), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('categoria_financeira', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conta_receber_categoria', 'contas_receber', ['categoria_financeira'], unique=False)
    op.create_index('idx_conta_receber_cliente_status', 'contas_receber', ['cliente_id', 'status'], unique=False)
    op.create_index('idx_conta_receber_emissao', 'contas_receber', ['data_emissao'], unique=False)
    op.create_index('idx_conta_receber_vencimento_status', 'contas_receber', ['data_vencimento', 'status'], unique=False)
    op.create_index('idx_conta_receber_venda', 'contas_receber', ['venda_id'], unique=False)
    op.create_index(op.f('ix_contas_receber_categoria_financeira'), 'contas_receber', ['categoria_financeira'], unique=False)
    op.create_index(op.f('ix_contas_receber_cliente_id'), 'contas_receber', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contas_receber_data_emissao'), 'contas_receber', ['data_emissao'], unique=False)
    op.create_index(op.f('ix_contas_receber_data_recebimento'), 'contas_receber', ['data_recebimento'], unique=False)
    op.create_index(op.f('ix_contas_receber_data_vencimento'), 'contas_receber', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_contas_receber_descricao'), 'contas_receber', ['descricao'], unique=False)
    op.create_index(op.f('ix_contas_receber_documento'), 'contas_receber', ['documento'], unique=False)
    op.create_index(op.f('ix_contas_receber_id'), 'contas_receber', ['id'], unique=False)
    op.create_index(op.f('ix_contas_receber_status'), 'contas_receber', ['status'], unique=False)
    op.create_index(op.f('ix_contas_receber_venda_id'), 'contas_receber', ['venda_id'], unique=False)
    op.create_table('fichas_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.Enum('GERAL', 'PARCIAL', 'ROTATIVO', name='tipoinventario'), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statusinventario'), nullable=False),
    sa.Column('usuario_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventario_data_geracao', 'fichas_inventario', ['data_geracao'], unique=False)
    op.create_index('idx_inventario_tipo_status', 'fichas_inventario', ['tipo', 'status'], unique=False)
    op.create_index(op.f('ix_fichas_inventario_data_geracao'), 'fichas_inventario', ['data_geracao'], unique=False)
    op.create_index(op.f('ix_fichas_inventario_id'), 'fichas_inventario', ['id'], unique=False)
    op.create_index(op.f('ix_fichas_inventario_status'), 'fichas_inventario', ['status'], unique=False)
    op.create_index(op.f('ix_fichas_inventario_tipo'), 'fichas_inventario', ['tipo'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('ie', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('contato_nome', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('conta', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fornecedor_cnpj', 'fornecedores', ['cnpj'], unique=False)
    op.create_index('idx_fornecedor_razao_social_ativo', 'fornecedores', ['razao_social', 'ativo'], unique=False)
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=True)
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_index(op.f('ix_fornecedores_razao_social'), 'fornecedores', ['razao_social'], unique=False)
    op.create_table('localizacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('CORREDOR', 'PRATELEIRA', 'PALLET', 'DEPOSITO', name='tipolocalizacao'), nullable=False),
    sa.Column('corredor', sa.String(length=20), nullable=True),
    sa.Column('prateleira', sa.String(length=20), nullable=True),
    sa.Column('nivel', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_localizacao_codigo', 'localizacoes_estoque', ['codigo'], unique=False)
    op.create_index('idx_localizacao_corredor_prateleira', 'localizacoes_estoque', ['corredor', 'prateleira', 'nivel'], unique=False)
    op.create_index('idx_localizacao_tipo_ativo', 'localizacoes_estoque', ['tipo', 'ativo'], unique=False)
    op.create_index(op.f('ix_localizacoes_estoque_ativo'), 'localizacoes_estoque', ['ativo'], unique=False)
    op.create_index(op.f('ix_localizacoes_estoque_codigo'), 'localizacoes_estoque', ['codigo'], unique=True)
    op.create_index(op.f('ix_localizacoes_estoque_id'), 'localizacoes_estoque', ['id'], unique=False)
    op.create_index(op.f('ix_localizacoes_estoque_tipo'), 'localizacoes_estoque', ['tipo'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('especialidades', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tecnico_cpf', 'tecnicos', ['cpf'], unique=False)
    op.create_index('idx_tecnico_nome_ativo', 'tecnicos', ['nome', 'ativo'], unique=False)
    op.create_index(op.f('ix_tecnicos_cpf'), 'tecnicos', ['cpf'], unique=True)
    op.create_index(op.f('ix_tecnicos_id'), 'tecnicos', ['id'], unique=False)
    op.create_index(op.f('ix_tecnicos_nome'), 'tecnicos', ['nome'], unique=False)
    op.create_index(op.f('ix_tecnicos_usuario_id'), 'tecnicos', ['usuario_id'], unique=False)
    op.create_table('tipos_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_padrao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tipo_servico_nome_ativo', 'tipos_servico', ['nome', 'ativo'], unique=False)
    op.create_index(op.f('ix_tipos_servico_id'), 'tipos_servico', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_servico_nome'), 'tipos_servico', ['nome'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('boletos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuracao_id', sa.Integer(), nullable=False),
    sa.Column('nosso_numero', sa.String(length=20), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('codigo_barras', sa.String(length=44), nullable=True),
    sa.Column('linha_digitavel', sa.String(length=54), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_juros', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_multa', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('data_baixa', sa.Date(), nullable=True),
    sa.Column('sacado_nome', sa.String(length=255), nullable=False),
    sa.Column('sacado_documento', sa.String(length=14), nullable=False),
    sa.Column('sacado_endereco', sa.String(length=500), nullable=True),
    sa.Column('sacado_cep', sa.String(length=8), nullable=True),
    sa.Column('sacado_cidade', sa.String(length=100), nullable=True),
    sa.Column('sacado_uf', sa.String(length=2), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.Column('demonstrativo', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ABERTO', 'REGISTRADO', 'PAGO', 'VENCIDO', 'CANCELADO', 'BAIXADO', name='statusboleto'), nullable=False),
    sa.Column('registrado', sa.Boolean(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracoes_boleto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boletos_data_vencimento'), 'boletos', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_boletos_id'), 'boletos', ['id'], unique=False)
    op.create_index(op.f('ix_boletos_nosso_numero'), 'boletos', ['nosso_numero'], unique=True)
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('data_orcamento', sa.DateTime(), nullable=False),
    sa.Column('validade_dias', sa.Integer(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'APROVADO', 'PERDIDO', 'CONVERTIDO', name='statusorcamento'), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orcamento_cliente', 'orcamentos', ['cliente_id', 'data_orcamento'], unique=False)
    op.create_index('idx_orcamento_data_status', 'orcamentos', ['data_orcamento', 'status'], unique=False)
    op.create_index('idx_orcamento_validade', 'orcamentos', ['data_validade', 'status'], unique=False)
    op.create_index('idx_orcamento_vendedor', 'orcamentos', ['vendedor_id', 'data_orcamento'], unique=False)
    op.create_index(op.f('ix_orcamentos_cliente_id'), 'orcamentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_data_orcamento'), 'orcamentos', ['data_orcamento'], unique=False)
    op.create_index(op.f('ix_orcamentos_data_validade'), 'orcamentos', ['data_validade'], unique=False)
    op.create_index(op.f('ix_orcamentos_id'), 'orcamentos', ['id'], unique=False)
    op.create_index(op.f('ix_orcamentos_status'), 'orcamentos', ['status'], unique=False)
    op.create_index(op.f('ix_orcamentos_vendedor_id'), 'orcamentos', ['vendedor_id'], unique=False)
    op.create_table('pedidos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('data_entrega_prevista', sa.Date(), nullable=False),
    sa.Column('data_entrega_real', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_frete', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'RECEBIDO_PARCIAL', 'RECEBIDO', 'CANCELADO', name='statuspedidocompra'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pedido_compra_data_entrega', 'pedidos_compra', ['data_entrega_prevista'], unique=False)
    op.create_index('idx_pedido_compra_data_pedido', 'pedidos_compra', ['data_pedido'], unique=False)
    op.create_index('idx_pedido_compra_fornecedor_status', 'pedidos_compra', ['fornecedor_id', 'status'], unique=False)
    op.create_index('idx_pedido_compra_status_data', 'pedidos_compra', ['status', 'data_entrega_prevista'], unique=False)
    op.create_index(op.f('ix_pedidos_compra_data_entrega_prevista'), 'pedidos_compra', ['data_entrega_prevista'], unique=False)
    op.create_index(op.f('ix_pedidos_compra_data_pedido'), 'pedidos_compra', ['data_pedido'], unique=False)
    op.create_index(op.f('ix_pedidos_compra_fornecedor_id'), 'pedidos_compra', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_pedidos_compra_id'), 'pedidos_compra', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_compra_status'), 'pedidos_compra', ['status'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('controla_lote', sa.Boolean(), nullable=False),
    sa.Column('controla_serie', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_produto_categoria_ativo', 'produtos', ['categoria_id', 'ativo'], unique=False)
    op.create_index('idx_produto_descricao', 'produtos', ['descricao'], unique=False)
    op.create_index(op.f('ix_produtos_categoria_id'), 'produtos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_produtos_codigo_barras'), 'produtos', ['codigo_barras'], unique=True)
    op.create_index(op.f('ix_produtos_descricao'), 'produtos', ['descricao'], unique=False)
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('transacoes_pix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.String(length=35), nullable=False),
    sa.Column('e2e_id', sa.String(length=32), nullable=True),
    sa.Column('chave_pix_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('pagador_nome', sa.String(length=255), nullable=True),
    sa.Column('pagador_documento', sa.String(length=14), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'PROCESSANDO', 'APROVADO', 'REJEITADO', 'CANCELADO', 'ESTORNADO', 'EXPIRADO', name='statuspagamento'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.Column('qr_code_texto', sa.Text(), nullable=True),
    sa.Column('qr_code_imagem', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('integration_id', sa.String(length=100), nullable=True),
    sa.Column('integration_provider', sa.String(length=50), nullable=True),
    sa.Column('integration_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chave_pix_id'], ['chaves_pix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_pix_chave_pix_id'), 'transacoes_pix', ['chave_pix_id'], unique=False)
    op.create_index(op.f('ix_transacoes_pix_data_criacao'), 'transacoes_pix', ['data_criacao'], unique=False)
    op.create_index(op.f('ix_transacoes_pix_e2e_id'), 'transacoes_pix', ['e2e_id'], unique=True)
    op.create_index(op.f('ix_transacoes_pix_id'), 'transacoes_pix', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_pix_integration_id'), 'transacoes_pix', ['integration_id'], unique=False)
    op.create_index(op.f('ix_transacoes_pix_txid'), 'transacoes_pix', ['txid'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'FINALIZADA', 'CANCELADA', name='statusvenda'), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_venda_cliente', 'vendas', ['cliente_id', 'data_venda'], unique=False)
    op.create_index('idx_venda_data_status', 'vendas', ['data_venda', 'status'], unique=False)
    op.create_index('idx_venda_vendedor', 'vendas', ['vendedor_id', 'data_venda'], unique=False)
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vendas_data_venda'), 'vendas', ['data_venda'], unique=False)
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    op.create_index(op.f('ix_vendas_status'), 'vendas', ['status'], unique=False)
    op.create_index(op.f('ix_vendas_vendedor_id'), 'vendas', ['vendedor_id'], unique=False)
    op.create_table('conciliacoes_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('transacao_pix_id', sa.Integer(), nullable=True),
    sa.Column('boleto_id', sa.Integer(), nullable=True),
    sa.Column('valor_sistema', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_extrato', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('diferenca', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('automatica', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boleto_id'], ['boletos.id'], ),
    sa.ForeignKeyConstraint(['transacao_pix_id'], ['transacoes_pix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conciliacoes_bancarias_id'), 'conciliacoes_bancarias', ['id'], unique=False)
    op.create_table('itens_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('localizacao_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_sistema', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_contada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('divergencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('justificativa', sa.String(length=500), nullable=True),
    sa.Column('conferido_por_id', sa.Integer(), nullable=True),
    sa.Column('data_contagem', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichas_inventario.id'], ),
    sa.ForeignKeyConstraint(['localizacao_id'], ['localizacoes_estoque.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_ficha_produto', 'itens_inventario', ['ficha_id', 'produto_id'], unique=False)
    op.create_index('idx_item_localizacao', 'itens_inventario', ['localizacao_id'], unique=False)
    op.create_index(op.f('ix_itens_inventario_ficha_id'), 'itens_inventario', ['ficha_id'], unique=False)
    op.create_index(op.f('ix_itens_inventario_id'), 'itens_inventario', ['id'], unique=False)
    op.create_index(op.f('ix_itens_inventario_localizacao_id'), 'itens_inventario', ['localizacao_id'], unique=False)
    op.create_index(op.f('ix_itens_inventario_produto_id'), 'itens_inventario', ['produto_id'], unique=False)
    op.create_table('itens_orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao_item', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_orcamento_produto', 'itens_orcamento', ['orcamento_id', 'produto_id'], unique=False)
    op.create_index(op.f('ix_itens_orcamento_id'), 'itens_orcamento', ['id'], unique=False)
    op.create_index(op.f('ix_itens_orcamento_orcamento_id'), 'itens_orcamento', ['orcamento_id'], unique=False)
    op.create_index(op.f('ix_itens_orcamento_produto_id'), 'itens_orcamento', ['produto_id'], unique=False)
    op.create_table('itens_pedido_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_solicitada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_recebida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_pedido_compra_pedido', 'itens_pedido_compra', ['pedido_id'], unique=False)
    op.create_index('idx_item_pedido_compra_produto', 'itens_pedido_compra', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_compra_id'), 'itens_pedido_compra', ['id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_compra_pedido_id'), 'itens_pedido_compra', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_compra_produto_id'), 'itens_pedido_compra', ['produto_id'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_venda_produto', 'itens_venda', ['venda_id', 'produto_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_id'), 'itens_venda', ['id'], unique=False)
    op.create_index(op.f('ix_itens_venda_produto_id'), 'itens_venda', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_venda_venda_id'), 'itens_venda', ['venda_id'], unique=False)
    op.create_table('lotes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('numero_lote', sa.String(length=50), nullable=False),
    sa.Column('data_fabricacao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('quantidade_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('documento_referencia', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lote_numero', 'lotes_estoque', ['numero_lote'], unique=False)
    op.create_index('idx_lote_produto_disponivel', 'lotes_estoque', ['produto_id', 'quantidade_atual'], unique=False)
    op.create_index('idx_lote_produto_validade', 'lotes_estoque', ['produto_id', 'data_validade'], unique=False)
    op.create_index(op.f('ix_lotes_estoque_created_at'), 'lotes_estoque', ['created_at'], unique=False)
    op.create_index(op.f('ix_lotes_estoque_data_validade'), 'lotes_estoque', ['data_validade'], unique=False)
    op.create_index(op.f('ix_lotes_estoque_id'), 'lotes_estoque', ['id'], unique=False)
    op.create_index(op.f('ix_lotes_estoque_numero_lote'), 'lotes_estoque', ['numero_lote'], unique=False)
    op.create_index(op.f('ix_lotes_estoque_produto_id'), 'lotes_estoque', ['produto_id'], unique=False)
    op.create_index(op.f('ix_lotes_estoque_quantidade_atual'), 'lotes_estoque', ['quantidade_atual'], unique=False)
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE', 'TRANSFERENCIA', 'DEVOLUCAO', name='tipomovimentacao'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('documento_referencia', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movimentacao_data_tipo', 'movimentacoes_estoque', ['created_at', 'tipo'], unique=False)
    op.create_index('idx_movimentacao_produto_data', 'movimentacoes_estoque', ['produto_id', 'created_at'], unique=False)
    op.create_index('idx_movimentacao_produto_tipo', 'movimentacoes_estoque', ['produto_id', 'tipo'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_created_at'), 'movimentacoes_estoque', ['created_at'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_documento_referencia'), 'movimentacoes_estoque', ['documento_referencia'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_id'), 'movimentacoes_estoque', ['id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_produto_id'), 'movimentacoes_estoque', ['produto_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_tipo'), 'movimentacoes_estoque', ['tipo'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', 'FATURADA', name='statusos'), nullable=False),
    sa.Column('descricao_problema', sa.Text(), nullable=True),
    sa.Column('descricao_solucao', sa.Text(), nullable=True),
    sa.Column('valor_mao_obra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['tipos_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_os_cliente_status', 'ordens_servico', ['cliente_id', 'status'], unique=False)
    op.create_index('idx_os_data_abertura', 'ordens_servico', ['data_abertura'], unique=False)
    op.create_index('idx_os_data_prevista', 'ordens_servico', ['data_prevista'], unique=False)
    op.create_index('idx_os_status', 'ordens_servico', ['status'], unique=False)
    op.create_index('idx_os_tecnico_status', 'ordens_servico', ['tecnico_id', 'status'], unique=False)
    op.create_index(op.f('ix_ordens_servico_cliente_id'), 'ordens_servico', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_data_abertura'), 'ordens_servico', ['data_abertura'], unique=False)
    op.create_index(op.f('ix_ordens_servico_id'), 'ordens_servico', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_produto_id'), 'ordens_servico', ['produto_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_status'), 'ordens_servico', ['status'], unique=False)
    op.create_index(op.f('ix_ordens_servico_tecnico_id'), 'ordens_servico', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_tipo_servico_id'), 'ordens_servico', ['tipo_servico_id'], unique=False)
    op.create_table('produtos_localizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('localizacao_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_minima', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantidade_maxima', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['localizacao_id'], ['localizacoes_estoque.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_localizacao_quantidade', 'produtos_localizacoes', ['localizacao_id', 'quantidade'], unique=False)
    op.create_index('idx_produto_localizacao', 'produtos_localizacoes', ['produto_id', 'localizacao_id'], unique=True)
    op.create_index(op.f('ix_produtos_localizacoes_id'), 'produtos_localizacoes', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_localizacoes_localizacao_id'), 'produtos_localizacoes', ['localizacao_id'], unique=False)
    op.create_index(op.f('ix_produtos_localizacoes_produto_id'), 'produtos_localizacoes', ['produto_id'], unique=False)
    op.create_table('apontamentos_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('horas_trabalhadas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_apontamento_data', 'apontamentos_horas', ['data'], unique=False)
    op.create_index('idx_apontamento_os_id', 'apontamentos_horas', ['os_id'], unique=False)
    op.create_index('idx_apontamento_tecnico_id', 'apontamentos_horas', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_apontamentos_horas_id'), 'apontamentos_horas', ['id'], unique=False)
    op.create_index(op.f('ix_apontamentos_horas_os_id'), 'apontamentos_horas', ['os_id'], unique=False)
    op.create_index(op.f('ix_apontamentos_horas_tecnico_id'), 'apontamentos_horas', ['tecnico_id'], unique=False)
    op.create_table('extratos_bancarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banco_codigo', sa.String(length=3), nullable=False),
    sa.Column('agencia', sa.String(length=10), nullable=False),
    sa.Column('conta', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('data_conciliacao', sa.DateTime(), nullable=True),
    sa.Column('conciliacao_id', sa.Integer(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=500), nullable=True),
    sa.Column('linha_arquivo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conciliacao_id'], ['conciliacoes_bancarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extratos_bancarios_banco_codigo'), 'extratos_bancarios', ['banco_codigo'], unique=False)
    op.create_index(op.f('ix_extratos_bancarios_conciliado'), 'extratos_bancarios', ['conciliado'], unique=False)
    op.create_index(op.f('ix_extratos_bancarios_data'), 'extratos_bancarios', ['data'], unique=False)
    op.create_index(op.f('ix_extratos_bancarios_id'), 'extratos_bancarios', ['id'], unique=False)
    op.create_table('itens_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_os_os_id', 'itens_os', ['os_id'], unique=False)
    op.create_index('idx_item_os_produto_id', 'itens_os', ['produto_id'], unique=False)
    op.create_index(op.f('ix_itens_os_id'), 'itens_os', ['id'], unique=False)
    op.create_index(op.f('ix_itens_os_os_id'), 'itens_os', ['os_id'], unique=False)
    op.create_index(op.f('ix_itens_os_produto_id'), 'itens_os', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_os_produto_id'), table_name='itens_os')
    op.drop_index(op.f('ix_itens_os_os_id'), table_name='itens_os')
    op.drop_index(op.f('ix_itens_os_id'), table_name='itens_os')
    op.drop_index('idx_item_os_produto_id', table_name='itens_os')
    op.drop_index('idx_item_os_os_id', table_name='itens_os')
    op.drop_table('itens_os')
    op.drop_index(op.f('ix_extratos_bancarios_id'), table_name='extratos_bancarios')
    op.drop_index(op.f('ix_extratos_bancarios_data'), table_name='extratos_bancarios')
    op.drop_index(op.f('ix_extratos_bancarios_conciliado'), table_name='extratos_bancarios')
    op.drop_index(op.f('ix_extratos_bancarios_banco_codigo'), table_name='extratos_bancarios')
    op.drop_table('extratos_bancarios')
    op.drop_index(op.f('ix_apontamentos_horas_tecnico_id'), table_name='apontamentos_horas')
    op.drop_index(op.f('ix_apontamentos_horas_os_id'), table_name='apontamentos_horas')
    op.drop_index(op.f('ix_apontamentos_horas_id'), table_name='apontamentos_horas')
    op.drop_index('idx_apontamento_tecnico_id', table_name='apontamentos_horas')
    op.drop_index('idx_apontamento_os_id', table_name='apontamentos_horas')
    op.drop_index('idx_apontamento_data', table_name='apontamentos_horas')
    op.drop_table('apontamentos_horas')
    op.drop_index(op.f('ix_produtos_localizacoes_produto_id'), table_name='produtos_localizacoes')
    op.drop_index(op.f('ix_produtos_localizacoes_localizacao_id'), table_name='produtos_localizacoes')
    op.drop_index(op.f('ix_produtos_localizacoes_id'), table_name='produtos_localizacoes')
    op.drop_index('idx_produto_localizacao', table_name='produtos_localizacoes')
    op.drop_index('idx_localizacao_quantidade', table_name='produtos_localizacoes')
    op.drop_table('produtos_localizacoes')
    op.drop_index(op.f('ix_ordens_servico_tipo_servico_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_tecnico_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_status'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_produto_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_data_abertura'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_cliente_id'), table_name='ordens_servico')
    op.drop_index('idx_os_tecnico_status', table_name='ordens_servico')
    op.drop_index('idx_os_status', table_name='ordens_servico')
    op.drop_index('idx_os_data_prevista', table_name='ordens_servico')
    op.drop_index('idx_os_data_abertura', table_name='ordens_servico')
    op.drop_index('idx_os_cliente_status', table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_movimentacoes_estoque_tipo'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_produto_id'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_id'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_documento_referencia'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_created_at'), table_name='movimentacoes_estoque')
    op.drop_index('idx_movimentacao_produto_tipo', table_name='movimentacoes_estoque')
    op.drop_index('idx_movimentacao_produto_data', table_name='movimentacoes_estoque')
    op.drop_index('idx_movimentacao_data_tipo', table_name='movimentacoes_estoque')
    op.drop_table('movimentacoes_estoque')
    op.drop_index(op.f('ix_lotes_estoque_quantidade_atual'), table_name='lotes_estoque')
    op.drop_index(op.f('ix_lotes_estoque_produto_id'), table_name='lotes_estoque')
    op.drop_index(op.f('ix_lotes_estoque_numero_lote'), table_name='lotes_estoque')
    op.drop_index(op.f('ix_lotes_estoque_id'), table_name='lotes_estoque')
    op.drop_index(op.f('ix_lotes_estoque_data_validade'), table_name='lotes_estoque')
    op.drop_index(op.f('ix_lotes_estoque_created_at'), table_name='lotes_estoque')
    op.drop_index('idx_lote_produto_validade', table_name='lotes_estoque')
    op.drop_index('idx_lote_produto_disponivel', table_name='lotes_estoque')
    op.drop_index('idx_lote_numero', table_name='lotes_estoque')
    op.drop_table('lotes_estoque')
    op.drop_index(op.f('ix_itens_venda_venda_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_venda_produto_id'), table_name='itens_venda')
    op.drop_index(op.f('ix_itens_venda_id'), table_name='itens_venda')
    op.drop_index('idx_item_venda_produto', table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_itens_pedido_compra_produto_id'), table_name='itens_pedido_compra')
    op.drop_index(op.f('ix_itens_pedido_compra_pedido_id'), table_name='itens_pedido_compra')
    op.drop_index(op.f('ix_itens_pedido_compra_id'), table_name='itens_pedido_compra')
    op.drop_index('idx_item_pedido_compra_produto', table_name='itens_pedido_compra')
    op.drop_index('idx_item_pedido_compra_pedido', table_name='itens_pedido_compra')
    op.drop_table('itens_pedido_compra')
    op.drop_index(op.f('ix_itens_orcamento_produto_id'), table_name='itens_orcamento')
    op.drop_index(op.f('ix_itens_orcamento_orcamento_id'), table_name='itens_orcamento')
    op.drop_index(op.f('ix_itens_orcamento_id'), table_name='itens_orcamento')
    op.drop_index('idx_item_orcamento_produto', table_name='itens_orcamento')
    op.drop_table('itens_orcamento')
    op.drop_index(op.f('ix_itens_inventario_produto_id'), table_name='itens_inventario')
    op.drop_index(op.f('ix_itens_inventario_localizacao_id'), table_name='itens_inventario')
    op.drop_index(op.f('ix_itens_inventario_id'), table_name='itens_inventario')
    op.drop_index(op.f('ix_itens_inventario_ficha_id'), table_name='itens_inventario')
    op.drop_index('idx_item_localizacao', table_name='itens_inventario')
    op.drop_index('idx_item_ficha_produto', table_name='itens_inventario')
    op.drop_table('itens_inventario')
    op.drop_index(op.f('ix_conciliacoes_bancarias_id'), table_name='conciliacoes_bancarias')
    op.drop_table('conciliacoes_bancarias')
    op.drop_index(op.f('ix_vendas_vendedor_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_status'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_data_venda'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.drop_index('idx_venda_vendedor', table_name='vendas')
    op.drop_index('idx_venda_data_status', table_name='vendas')
    op.drop_index('idx_venda_cliente', table_name='vendas')
    op.drop_table('vendas')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_transacoes_pix_txid'), table_name='transacoes_pix')
    op.drop_index(op.f('ix_transacoes_pix_integration_id'), table_name='transacoes_pix')
    op.drop_index(op.f('ix_transacoes_pix_id'), table_name='transacoes_pix')
    op.drop_index(op.f('ix_transacoes_pix_e2e_id'), table_name='transacoes_pix')
    op.drop_index(op.f('ix_transacoes_pix_data_criacao'), table_name='transacoes_pix')
    op.drop_index(op.f('ix_transacoes_pix_chave_pix_id'), table_name='transacoes_pix')
    op.drop_table('transacoes_pix')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_descricao'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_codigo_barras'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria_id'), table_name='produtos')
    op.drop_index('idx_produto_descricao', table_name='produtos')
    op.drop_index('idx_produto_categoria_ativo', table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pedidos_compra_status'), table_name='pedidos_compra')
    op.drop_index(op.f('ix_pedidos_compra_id'), table_name='pedidos_compra')
    op.drop_index(op.f('ix_pedidos_compra_fornecedor_id'), table_name='pedidos_compra')
    op.drop_index(op.f('ix_pedidos_compra_data_pedido'), table_name='pedidos_compra')
    op.drop_index(op.f('ix_pedidos_compra_data_entrega_prevista'), table_name='pedidos_compra')
    op.drop_index('idx_pedido_compra_status_data', table_name='pedidos_compra')
    op.drop_index('idx_pedido_compra_fornecedor_status', table_name='pedidos_compra')
    op.drop_index('idx_pedido_compra_data_pedido', table_name='pedidos_compra')
    op.drop_index('idx_pedido_compra_data_entrega', table_name='pedidos_compra')
    op.drop_table('pedidos_compra')
    op.drop_index(op.f('ix_orcamentos_vendedor_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_status'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_data_validade'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_data_orcamento'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_cliente_id'), table_name='orcamentos')
    op.drop_index('idx_orcamento_vendedor', table_name='orcamentos')
    op.drop_index('idx_orcamento_validade', table_name='orcamentos')
    op.drop_index('idx_orcamento_data_status', table_name='orcamentos')
    op.drop_index('idx_orcamento_cliente', table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_boletos_nosso_numero'), table_name='boletos')
    op.drop_index(op.f('ix_boletos_id'), table_name='boletos')
    op.drop_index(op.f('ix_boletos_data_vencimento'), table_name='boletos')
    op.drop_table('boletos')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tipos_servico_nome'), table_name='tipos_servico')
    op.drop_index(op.f('ix_tipos_servico_id'), table_name='tipos_servico')
    op.drop_index('idx_tipo_servico_nome_ativo', table_name='tipos_servico')
    op.drop_table('tipos_servico')
    op.drop_index(op.f('ix_tecnicos_usuario_id'), table_name='tecnicos')
    op.drop_index(op.f('ix_tecnicos_nome'), table_name='tecnicos')
    op.drop_index(op.f('ix_tecnicos_id'), table_name='tecnicos')
    op.drop_index(op.f('ix_tecnicos_cpf'), table_name='tecnicos')
    op.drop_index('idx_tecnico_nome_ativo', table_name='tecnicos')
    op.drop_index('idx_tecnico_cpf', table_name='tecnicos')
    op.drop_table('tecnicos')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_localizacoes_estoque_tipo'), table_name='localizacoes_estoque')
    op.drop_index(op.f('ix_localizacoes_estoque_id'), table_name='localizacoes_estoque')
    op.drop_index(op.f('ix_localizacoes_estoque_codigo'), table_name='localizacoes_estoque')
    op.drop_index(op.f('ix_localizacoes_estoque_ativo'), table_name='localizacoes_estoque')
    op.drop_index('idx_localizacao_tipo_ativo', table_name='localizacoes_estoque')
    op.drop_index('idx_localizacao_corredor_prateleira', table_name='localizacoes_estoque')
    op.drop_index('idx_localizacao_codigo', table_name='localizacoes_estoque')
    op.drop_table('localizacoes_estoque')
    op.drop_index(op.f('ix_fornecedores_razao_social'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_index('idx_fornecedor_razao_social_ativo', table_name='fornecedores')
    op.drop_index('idx_fornecedor_cnpj', table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_fichas_inventario_tipo'), table_name='fichas_inventario')
    op.drop_index(op.f('ix_fichas_inventario_status'), table_name='fichas_inventario')
    op.drop_index(op.f('ix_fichas_inventario_id'), table_name='fichas_inventario')
    op.drop_index(op.f('ix_fichas_inventario_data_geracao'), table_name='fichas_inventario')
    op.drop_index('idx_inventario_tipo_status', table_name='fichas_inventario')
    op.drop_index('idx_inventario_data_geracao', table_name='fichas_inventario')
    op.drop_table('fichas_inventario')
    op.drop_index(op.f('ix_contas_receber_venda_id'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_status'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_id'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_documento'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_descricao'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_data_vencimento'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_data_recebimento'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_data_emissao'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_cliente_id'), table_name='contas_receber')
    op.drop_index(op.f('ix_contas_receber_categoria_financeira'), table_name='contas_receber')
    op.drop_index('idx_conta_receber_venda', table_name='contas_receber')
    op.drop_index('idx_conta_receber_vencimento_status', table_name='contas_receber')
    op.drop_index('idx_conta_receber_emissao', table_name='contas_receber')
    op.drop_index('idx_conta_receber_cliente_status', table_name='contas_receber')
    op.drop_index('idx_conta_receber_categoria', table_name='contas_receber')
    op.drop_table('contas_receber')
    op.drop_index(op.f('ix_contas_pagar_status'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_id'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_fornecedor_id'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_documento'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_descricao'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_data_vencimento'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_data_pagamento'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_data_emissao'), table_name='contas_pagar')
    op.drop_index(op.f('ix_contas_pagar_categoria_financeira'), table_name='contas_pagar')
    op.drop_index('idx_conta_pagar_vencimento_status', table_name='contas_pagar')
    op.drop_index('idx_conta_pagar_fornecedor_status', table_name='contas_pagar')
    op.drop_index('idx_conta_pagar_emissao', table_name='contas_pagar')
    op.drop_index('idx_conta_pagar_categoria', table_name='contas_pagar')
    op.drop_table('contas_pagar')
    op.drop_index(op.f('ix_configuracoes_boleto_id'), table_name='configuracoes_boleto')
    op.drop_table('configuracoes_boleto')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_index('idx_cliente_nome_ativo', table_name='clientes')
    op.drop_index('idx_cliente_data_nascimento', table_name='clientes')
    op.drop_index('idx_cliente_cpf_cnpj', table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_chaves_pix_id'), table_name='chaves_pix')
    op.drop_index(op.f('ix_chaves_pix_chave'), table_name='chaves_pix')
    op.drop_table('chaves_pix')
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
